### ISSUE TITLE
Missing SVG for Date and Clock in the icons folder

### ISSUE THREAD

**Issue by Kaiserdragon2** [Arcticons-Team/Arcticons#1573]
Some of the Icons used for widget preview and dynamic clock aren't present as svg in the icons folder if someones wants to make a different color profile these can't be automatically be processed.
This are the icons ☟.
![image](https://github.com/Donnnno/Arcticons/assets/8929967/c434a38d-1369-4bb7-8b20-d66cd619c04f)

**Comment by Donnnno** [comment]
oh yeah, I might have them somewhere on my pc! I'll upload them soon.

Also thinking about making some nice new watch faces.

**Comment by Donnnno** [comment]
So I lost the widget previews.... but those are easy to recreate luckily 

you can find other files here https://github.com/Donnnno/Arcticons/tree/main/templates/app%20files

**Comment by Kaiserdragon2** [comment]
There is something wrong with the clock digital preview
![image](https://github.com/Donnnno/Arcticons/assets/8929967/f09cfcc5-1a19-46e8-a4bc-624877e9ef76)

**Comment by Donnnno** [comment]
O

**Comment by Kaiserdragon2** [comment]
![image](https://github.com/Donnnno/Arcticons/assets/8929967/a42fbe0e-ec6f-4765-b1ca-a258c1f00b3b)
Do you have the svg as well then we could add them as xml in the main res folder and have them colored like the ic_idea in every variant.

**Comment by Donnnno** [comment]
Yeah I still have these somewhere
