### ISSUE TITLE
[Widgets] Use the Quicksand font in the widgets instead of the default android one

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#1599]

**Comment by Aman9das** [comment]
Need to edit the ttf files at https://github.com/Donnnno/Arcticons/tree/main/app/src/main/res/font I think

**Comment by Donnnno** [comment]
@Aman9das checked that already, but the ttf files work as they should.

I read somewhere that widgets use the default android font unless specified somehow within the code, so gotta find a way to do that I guess

**Comment by kaanelloed** [comment]
@Donnnno It seems that the possibility of using a custom font in a widget has been removed by Google for security reasons.

https://issuetracker.google.com/issues/190444596
