### ISSUE TITLE
Off-Center Icons

### ISSUE THREAD

**Issue by raycadle** [Arcticons-Team/Arcticons#1648]
First off, I just want to say thank you for the amazing icon pack. Made my Pixel so much nicer to look at. Keep up the great work!

On a different note, however, I noticed a minor bug in some icons. A couple FOSS apps — Newpipe and Retro Music Player — have their icons off-centered and it's really tripping out my OCD. I'm using Lawnchair 2 as launcher and never had the icons off-centered with the stock icons.

![Screenshot_20230811-085906~2](https://github.com/Donnnno/Arcticons/assets/93884664/6fa5e82e-4dd5-4a40-9701-e4a2e1d7d1b3)
![Screenshot_20230811-085941~2](https://github.com/Donnnno/Arcticons/assets/93884664/0f4f5752-b4e5-4d61-87cc-7d8c87600e4f)

As you may notice, Retro isn't severely off-centered, however, Newpipe is very noticable. I don't want to rush anyone to fix this. I just didn't see a related issue open so I thought I would bring it up, in hopes that it silently gets fixed in a future update.

With that said, thanks a bunch and have a great rest of your day! Blessings to you and yours.

**Comment by Donnnno** [comment]
Ah, that's a good one. I'm gonna take a look at it. From what I can tell, the triangular icons are probably aligned in the middle. But they should be bumped a little to the right so that it's optically in the middle.

**Comment by dgcampbe** [comment]
Perhaps we could find a way to make a script automatically align icons to ensure that all of them are mathematically perfectly centered. When I create icons, I am not always sure exactly what point should be in the center, so I kinda eyeball it.

**Comment by Donnnno** [comment]
In this case, you actually want it to be slightly off centered hahah, so a script cant do that. Also, all shapes have to be grouped (or made a compound path) properly.

**Comment by Donnnno** [comment]
I also think this is an Arcticons You specific problem, it never bothered me with the regular versions, but it makes sense for the You version to be modified a bit.

**Comment by Donnnno** [comment]
This is a difficult one because of all the different sizes of the adaptive shapes.

**Comment by wwwwwwari** [comment]
I wonder if this only happens with triangular shaped icons?

**Comment by Donnnno** [comment]
Yes

**Comment by Donnnno** [comment]
![image](https://github.com/Donnnno/Arcticons/assets/31142286/e90f3c63-e118-4687-af70-a4cf5b3c46b3)

this is better already

**Comment by KR4U7H3R** [comment]
The newpipe icon in the current version looks a lot like before your improvement. Is it possible that the change got reverted?

<img width="444" height="227" alt="Image" src="https://github.com/user-attachments/assets/31c06469-839a-4247-b9db-92f84b6c0820" />

PS: Actually while loking at it in with this zoom it looks similar... Not great, but I guess it is fine.
