### ISSUE TITLE
[You] Custom picked app icons in launchers aren't dynamic

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#1679]
For example:

I've changed the middle icon here, and chose another dynamic theme style.

![image](https://github.com/Donnnno/Arcticons/assets/31142286/ac7d16bd-3c8c-426d-b7f2-11e0dfd25a93)

Probably external, but might be worth it to contact other devs.
Link to Nova Discord support thread. 
https://discord.com/channels/466300922767736844/1146750269535821866.

**Comment by Donnnno** [comment]
Expected behavior in Nova, but they might change it soon.

**Comment by ThatOneCalculator** [comment]
Can't repro in kvaestito, external

**Comment by Donnnno** [comment]
Thanks for checking, every launcher probably has its own implementation. Kvaestito has lost of cool features for icon packs, so that explains it probably.
