### ISSUE TITLE
Multiple Icons for Single App. (Based on System Theme)

### ISSUE THREAD

**Issue by BaruaAtish** [Arcticons-Team/Arcticons#1753]
Hello, I want to help contribute to Arcticons by submitting icons I create for an app called "DualWallpaper". The issue is, DualWallpaper changes icons based on system theme. I have created icons for both versions but do not know how to name and add them to the others folder and how to list them in the xml. Any help would be appreciated. Thank you!

**Comment by Donnnno** [comment]
Have you tried getting it with Icon Request? https://github.com/Kaiserdragon2/IconRequest/releases

Maybe it's different when you change the mode; otherwise, automatic switching isn't possible.

We can still add both tho!

**Comment by Kaiserdragon2** [comment]
I have tested it out and it is possible to do as you can see with the following debug apk.
[Debug-apk.zip](https://github.com/Donnnno/Arcticons/files/13259294/Debug-apk.zip)
But the current setup doesn't allow for this kind of build and there need to be some file manually moved and renamed.
I don't know if it is worth to change the script to allow for such builds.

**Comment by Donnnno** [comment]
As far as I know, this is only possible when the dev uses different activities for the icons. If not, it's not possible for the icon pack to switch between icons.
