### ISSUE TITLE
Could custom themepicker be added for  you icons?

### ISSUE THREAD

**Issue by Anonymous2716** [Arcticons-Team/Arcticons#1772]
For example I am on Android 9 and don't have themed icon feature. It would be great to have a theme picker. By default I have monochromatic white background and dark foreground for icons. Thanks.

**Comment by Donnnno** [comment]
That sounds really cool, but unfortunately beyond my knowledge. But who knows, maybe someone else might know how :-)

**Comment by kaanelloed** [comment]
I don't think this is directly possible, but in the latest version of Iconeration, if you select Arcticons You in Icon Pack, select your colors, check Themed Icons, refresh the list and build the icon pack, you'll get what you want.

The disadvantage is that you have to repeat these steps if you want to change something.

https://codeberg.org/kaanelloed/Iconeration/releases

**Comment by Donnnno** [comment]
Closing this! But wrote something about it:
https://docs.arcticons.com/faq#can-you-make-a-custom-color-option-inside-arcticons
