### ISSUE TITLE
Create an Arcticons 'organization' for all Arcticons projects.

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#1799]
I really would like an Arcticons organization, but the username is taken, unfortunately.

I don't know if this works but, hey @arcticons I would really like to have your username for our project. Please contact me here or per mail: arcticons@onnno.nl . Thanks in advance. :)

**Comment by kaanelloed** [comment]
My personal impression is that this account was created but never used. And Github no longer allows people to claim an inactive username. So you'll probably have to use an alternative name like ArcticonsProjects or ArcticonsTeam.

**Comment by dgcampbe** [comment]
It is possible to rename a GitHub organization, it appears, so you could just pick one now and change it later.

**Comment by Donnnno** [comment]
https://github.com/Arcticons-Team lets goooo

**Comment by Donnnno** [comment]
Moving this repo after the F-Droid build process, don't want it to cause any errors

**Comment by Donnnno** [comment]
![Screenshot_20231226_124124_F-Droid.jpg](https://github.com/Donnnno/Arcticons/assets/31142286/16d46757-08ba-442b-9ec5-3f75382aa2fe)

🤔

**Comment by dgcampbe** [comment]
Is this ready to be marked done?
