### ISSUE TITLE
XML-drawable compatible launchers

### ISSUE THREAD

**Issue by Kaiserdragon2** [Arcticons-Team/Arcticons#1832]
I want to check if there are any launcher which have issues xml icons. If you could check on your launcher or sent me some launchers so i can test it.
[Arcticons lightXml.zip](https://github.com/Donnnno/Arcticons/files/13463697/Arcticons.lightXml.zip)
[ArcticonsDarkXml.zip](https://github.com/Donnnno/Arcticons/files/13463708/ArcticonsDarkXml.zip)

**Comment by Donnnno** [comment]
We might wanna test all the launchers that we're showing in our apply tab. From what I remember, Microsoft Launcher had issues with XML.

**Comment by Kaiserdragon2** [comment]
List of Launchers 
- [ ] Action   (Does support adaptive xml (you) but not xml)
- [X] ADW
- [X] Apex 
- [ ] Before
- [ ] BlackBerry
- [ ] CM Theme
- [X]  Flick
- [X] Go Ex 
- [ ] Hios
- [ ] Holo
- [ ] Holo HD
- [ ] Hyperion
- [ ] Kiss
- [X] Kvaesitso
- [ ] Lawnchair
- [ ] Lucid
- [ ] Microsoft
- [ ] Niagara
- [ ] Nougat
- [ ] Nova
- [ ] OxygenOS
- [ ] Poco
- [ ] Samsung One UI
- [ ] Smart
- [ ] Solo
- [ ] Square
- [ ] TinyBit
- [ ] ZenUI

**Comment by Donnnno** [comment]
We can remove launchers that aren't updated in ages from the list if we want

**Comment by Donnnno** [comment]
Not a fan of having even more versions currently, maybe only an adaptive dark/light version.

**Comment by Kaiserdragon2** [comment]
> Not a fan of having even more versions currently, maybe only an adaptive dark/light version.

I also don't think more versions are a good idea especially if they are literally the same. An adaptive dark/light might be nice especially considering that it has been requested before.

**Comment by Kaiserdragon2** [comment]
> We can remove launchers that aren't updated in ages from the list if we want

i think this would be a good idea if users from a phone with a native launcher that doesn't support icon packs wants to to pick one from the list they should be reasonable compatible with current android versions and the share for android api 21 - 23 is really small.

I think for a switch to xml at least Microsoft launcher should support it too. Overall the suppor isn't bad.

**Comment by Donnnno** [comment]
Why does it always gotta be a Microsoft thing 😆

**Comment by Kaiserdragon2** [comment]
> > I think for a switch to xml at least Microsoft launcher should support it too.
> 
> Just give the trillion dollar company a bit more time.

More Money, More People, More Slower

**Comment by Kaiserdragon2** [comment]
### XML Launcher Support

**Partial: (3)**


- [ ] Action ('Material You' only)
- [ ] Apex (Confirmation/Feedback needed)
- [ ] Lawnchair (Alpha Version only)

**Fully supported: (15)**

- [ ] ADW
- [ ] Flick
- [ ] Go Ex
- [ ] Hios
- [ ] Hyperion
- [ ] Kiss
- [ ] Kvaesitso
- [ ] Niagara
- [ ] Nougat
- [ ] Nothing
- [ ] Nova
- [ ] Poco
- [ ] Smart
- [ ] Square
- [ ] TinyBit

**EOL/Unknown (Feedback/Testing needed): (6)**

- [ ] BlackBerry
- [ ] CM Theme
- [ ] Holo (Requires old Android Versions)
- [ ] Holo HD (Requires old Android Versions)
- [ ] OpenLauncher
- [ ] Solo (Crashing on available Test Devices)

**Untested: (26)**

- [ ] Arrow
- [ ] ASAP
- [ ] Atom
- [ ] Aviate
- [ ] Before
- [ ] Evie
- [ ] Go
- [ ] K
- [ ] LGHome
- [ ] Lime
- [ ] Lynx
- [ ] M
- [ ] Mesh
- [ ] Mini
- [ ] Minimalist
- [ ] New
- [ ] Next
- [ ] Pear
- [ ] Pixel Launcher ( [Mods](https://github.com/KieronQuinn/PixelLauncherMods) & [Extended](https://github.com/saitamasahil/Pixel-Launcher-Extended) )
- [ ] OxygenOS
- [ ] One UI
- [ ] V
- [ ] Z
- [ ] ZenUI
- [ ] Zero

**Not Supported: (2*)**

- [ ] Lucid
- [ ] Microsoft

Don't support icon packs in general

- [ ] Pixel Launcher
- [ ] ABC

### Apps with Icon Pack Support

**Supported:**

- [ ] [Icon Request](https://github.com/Kaiserdragon2/IconRequest)
- [ ] [MicoPacks](https://github.com/ukanth/micopacks)

Not Supported:

- [ ] [Hail](https://github.com/aistra0528/Hail)

**Currently known:**
52 Launcher
03 Apps

**Comment by Donnnno** [comment]
Many people ask if Arcticons supports GrapheneOS Launcher, but that launcher doesn't support icon packs in general, so it can go on the list as doesn't support icon packs :)

**Comment by Donnnno** [comment]
OneUI requires an app called Theme Park to be installed to use icon packs

**Comment by Donnnno** [comment]
Iconeration is basically a companion app for Arcticons: https://fosstodon.org/home

**Comment by Donnnno** [comment]
There's also Wheel Launcher (Lawnchair fork), the dev contacted me a while ago to ask if it's possible to bundle Arcticons with the Launcher: http://wheellauncher.com/

**Comment by Donnnno** [comment]
I've gotten a response from the MS Launcher devs, pretty general, but who knows!

> We are always working to add more sources in the updates. Thank you for sharing your thoughts with us.
>
> We would consider and discuss your suggestion.

**Comment by Donnnno** [comment]
Planning to merge this with #1874
