### ISSUE TITLE
Inclusion of "Launcher hidden" entries for Apps with Icon Pack support

### ISSUE THREAD

**Issue by TotallyAvailable** [Arcticons-Team/Arcticons#1873]
As I seem to remember a discussion/removal of Icons linked to WebApps (unless I picked that up somewhere else...) I thought about actually asking before I start something big that won't make it.

What are your thoughts on including entries that won't show up in a Launcher but get picked up by [Apps with Icon Pack support](https://github.com/Donnnno/Arcticons/issues/1832#issuecomment-1826812146) ?

**Comment by Donnnno** [comment]
Can you give an example of an app like that? 

Web apps are allowed if someone makes it, but they're disabled in the request function because of their unique IDs

**Comment by kaanelloed** [comment]
I've never really looked at web apps icons, but from what I understand, I don't think any launcher has implemented a way to apply icon packs with web apps.
