### ISSUE TITLE
Size difference between Day & Night and Material You 

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#1883]
I noticed a 10mb difference between Day & Night and Material You, looks pretty strange since they're basically the same versions.

![image](https://github.com/Donnnno/Arcticons/assets/31142286/56d60f9a-78fe-4866-ba2e-01f9f2d4c656)

Might have something to do with the Android Studio builder?

**Comment by petlyh** [comment]
7-zip shows uncompressed sizes of 46.9 MB (dayNight) and 46.1 MB (you). While both flavors use XML instead of PNG they have different structures, so I think the size difference is just the result of one of them being more compressible.

**Comment by Donnnno** [comment]
That's some wild compression then, thanks for the logical explanation!
