### ISSUE TITLE
Assistance on Converting Icon

### ISSUE THREAD

**Issue by andrew-aiken** [Arcticons-Team/Arcticons#1888]
What would be the best way to convert this logo?

https://mangolanguages.com/wp-content/uploads/2022/05/ML-Logo-Header.svg

Converting it to lines seems very bulky

![image](https://github.com/Donnnno/Arcticons/assets/61951628/3d05ecf6-617d-44f2-84b7-0fe30dea643e)

**Comment by Kaiserdragon2** [comment]
I think it might work out like this, but if you think the lines are to dense you could reduce some of the lines like this ↓
![image](https://github.com/Arcticons-Team/Arcticons/assets/8929967/f5c8d4e7-a37e-44f1-a548-265562542551)

**Comment by andrew-aiken** [comment]
Thanks for the feedback @Kaiserdragon2
