### ISSUE TITLE
Apps listed both in appfilter.xml and requests.txt

### ISSUE THREAD

**Issue by alchemiker** [Arcticons-Team/Arcticons#1904]
Hello, I noticed that WallFlow and WallFlow Plus, which were added in the last version (not by me) are listed in both lists, maybe even more apps. I guess that the creation of the requests.txt file somehow went wrong.
I checked for WallFlow Plus, at least for this one the intent filter is exactly identical in both files.

**Comment by alchemiker** [comment]
Hi @TotallyAvailable thank you very much for your answer! Do you mean that the list wasn't updated after the new version came out, or that there is a mistake?

Thanks for pointing out "mucke", I just created an icon for it yesterday (but didn't upload it so far...) 
I will try to find out which script compares the entries from the requests.txt-file with the appfilter.xml-file and whether the results are reproducible for me.

If you have more examples of doubled app icons, please write them here, so others can test their bug fixes against the known duplicates.

**Comment by Kaiserdragon2** [comment]
From the looks of the commits the script isn't be executed since adding these icons this would explain why the still are there

**Comment by Donnnno** [comment]
I know that the current list is beyond saving, but I can't imagine how a “priority request light” system would work. Before the Play store releases, we used to do it with GitHub issues, but that was even worse 😅

**Comment by Donnnno** [comment]
The list has been updated just now :)

**Comment by Donnnno** [comment]
Ehh, I think the current popularity based system works the best. The file may be heavy, but that's just a downside to it.

**Comment by alchemiker** [comment]
> Ehh, I think the current popularity based system works the best. The file may be heavy, but that's just a downside to it.

The thing is, that there are many "corpses" in the list. For example, when searching for the activity names of some popular games, I found many entries from a while ago, which were wished once or twice, which are called something slightly different yet similar to the original game, and are not to be found in any of the stores (anymore?). I suppose they were plagiated versions that were taken down quickly, but had their little boom and were installed by people. Also apps of companies that no longer exist, etc.

My heretic suggestion would be to kick out old entries. The oldest is from 1. April 2022. If a hard cut seems too harsh, we could make a shuffeled system: entries that were requested just once after half a year, entries that were wished twice after a year, entries that were wished three times after two years... you could then also allow for more requests per person, then you would get more accurate data about how often which apps are needed. 

I will try to make some calculations to see what effect it would have on the volume. If we had a real data science pro at hand, we could calculate a rate of requests per month and the probability that the app was wished before, and based on this calculate ideal times and numbers of requests... a real-life modelling problem, my old math teacher would be so excited!
