### ISSUE TITLE
Malformed component info in appfilter.xml

### ISSUE THREAD

**Issue by alchemiker** [Arcticons-Team/Arcticons#1924]
Hey, as a side-effect of going through the xml file with a regex I found some entries which do not have the general form of:

    ComponentInfo{<something>/<something>}

These are the entries:

    ComponentInfo{com.mobillium.airalo.ui.splash.SplashActivity}
    ComponentInfo{com.fenoxo.coc2}
    ComponentInfo{com.fenoxo.coc2.MainActivity}
    ComponentInfo{me.tigerhix.cytoid}
    ComponentInfo{me.tigerhix.cytoid.CytoidPluginActivity}
    ComponentInfo{com.lge.updatecentre/com.lge.updatecentre.UpdateCentrePrfActivity
    ComponentInfo{com.android.stk/com.android.stk.StkLauncherActivity1

The last two ones are apparently only missing a closing bracket, and for two of them I would make a guess to assemble them to

    ComponentInfo{com.fenoxo.coc2/com.fenoxo.coc2.MainActivity}

and 

    ComponentInfo{me.tigerhix.cytoid/me.tigerhix.cytoid.CytoidPluginActivity}

but what to do with the first entry?

**Comment by alchemiker** [comment]
Thank you very much for your answer! With your help I fixed now these entries 👍 I also wasn't clever enough to look whether there are other entries for this app, too... that would have answered this question in first place, of course 😅

**Comment by Donnnno** [comment]
Great work :)
