### ISSUE TITLE
Arcticons Day/Night Does Not Apply Icons

### ISSUE THREAD

**Issue by Caljay** [Arcticons-Team/Arcticons#1935]
As the title says Arcticons Day/Night does not properly apply icons when used on Xperia 5 III with Microsoft launcher. Tried it on both light and dark mode with no difference. The separate apps for Day and Light do work properly but Arcticons Material You has the same issue with no icons being applied.

**Device Details:**
Sony Xperia 5 III
Android 13
Microsoft Launcher

**Comment by Donnnno** [comment]
Hi @Caljay as @TotallyAvailable already mentioned, Microsoft Launcher currently lacks modern icon pack features. If you really want to see Arcticons Day/Night work with MS Launcher, I'd suggest leaving feedback :)
