### ISSUE TITLE
XML error in appfilter 

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#1942]
I wanted to test the latest build, but the appfilter corrupts when it gets sorted by the preparerelease script

**Comment by Kaiserdragon2** [comment]
I will look into it later today

**Comment by Donnnno** [comment]
Thanks @petlyh ! how did you find it?

**Comment by Donnnno** [comment]
Fixing the line resolved the problem!

**Comment by petlyh** [comment]
> how did you find it?

Old reliable `git bisect`. It's incredibly useful for things like this.

**Comment by Donnnno** [comment]
> Should be another thing possibly looked for by the script like duplicates and missing drawables ? Check if every '!' has a '<' in front ?

Good suggestion, looks like @Kaiserdragon2 did some scripting magic again to implement this :)
