### ISSUE TITLE
Further enhancements to the prepare release script

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#1985]
We can make our fantastic script even more powerfull with these changes:

- newdrawables is not deleted upon generation

![image](https://github.com/Arcticons-Team/Arcticons/assets/31142286/29e6f8ea-47aa-41a5-b663-d0c52f5e4464)

- Motorola support: https://github.com/zixpo/candybar/pull/174
by copying and renaming appfilter to icon_config.xml we can add support for moto devices!

- the 'other' folder with empty icons doesn't update the appfilter in res & assets (this might be something only on my end)

**Comment by Kaiserdragon2** [comment]
Appfilter is updated through android studio at build.
The new drawable file is needed to ensure the new category stays the same if the app is rebuilt in case of a fix

**Comment by Kaiserdragon2** [comment]
I can add the the icon_config file to the preparehelper script
