### ISSUE TITLE
Restructure the 'other' folder

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#1986]
other is kinda a undescriptive name for the folder/

- I think it should be something like newicons
idk if it's logical to have requests.txt and appfilter.xml in there then
- scripts should be a folder at the top level

**Comment by Kaiserdragon2** [comment]
I think the appfilter file should be in the same path like the newicons so contribute especially new ones have one folder to go to.
The other files could be easily moved especially with the planned change for the request site, the request file must not be that accessible. The scripts at the top is a good idea.

**Comment by Donnnno** [comment]
Works for me
