### ISSUE TITLE
The linked arcticons.com/ Url does not work

### ISSUE THREAD

**Issue by Kaiserdragon2** [Arcticons-Team/Arcticons#1988]
The linked arcticons.com/ Url does not work

**Comment by Donnnno** [comment]
Uhh yeah I was looking into that too...

**Comment by Donnnno** [comment]
So this is an annoying thing that's haunting me for many years. Arcticons.com redirects to my own site, saves money on hosting I guess.

So by default it's a http link.
http://arcticons.com/

The thing is that GitHub and some other sites automatically change it to https

**Comment by Kaiserdragon2** [comment]
i think instead of redirecting there should be an cname entry for arcticons,com that points to your site

**Comment by Donnnno** [comment]
Talked to my hosting company, domains only don't have SSL certificates. So they recommended that I use something like redirect.pizza, so I'll look into that.
