### ISSUE TITLE
Github Action can't create File

### ISSUE THREAD

**Issue by Kaiserdragon2** [Arcticons-Team/Arcticons#1992]
It worked for the test an my fork 
I think it is some kind of permission issue
Could you check this again or if there is something similar 
![image](https://github.com/Arcticons-Team/Arcticons/assets/8929967/159d685d-64fd-48f1-b5e0-a380ed79dd79)

**Comment by Donnnno** [comment]
I've added 
`permissions: write-all read-all`
hope that works
https://github.com/Arcticons-Team/Arcticons/commit/922713140f50ac7dd99ca973250b98822ec28bff

**Comment by Donnnno** [comment]
> I've added `permissions: write-all read-all` hope that works [9227131](https://github.com/Arcticons-Team/Arcticons/commit/922713140f50ac7dd99ca973250b98822ec28bff)

Reverted this because it wasn't the right way

This is how it looks now:

![image](https://github.com/Arcticons-Team/Arcticons/assets/31142286/843e0fe1-6b2e-4a96-b8c9-732b2627522b)

**Comment by Kaiserdragon2** [comment]
The settings look good
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job this seems to be our problem if i understand this correctly 
and the Send write tokens to workflows from pull requests setting is not selected, the permissions are adjusted to change any write permissions to read only.
