### ISSUE TITLE
FFupdater icon not applied

### ISSUE THREAD

**Issue by Elaborendum** [Arcticons-Team/Arcticons#1994]
FFUpdater has an icon in this pack, but it isn't applied. Even though it seems that in appfitlter it points to the correct one (de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.activity.main.MainActivity)

**Comment by Donnnno** [comment]
Hi! Some questions:
- what launcher are you using?
- have you tried to reapply arcticons in the launchers settings
- did you test it with another launcher?
- have you tried clearing your cache?

**Comment by Donnnno** [comment]
Just installed FF Updater from F-Droid, the icon is appearing for me Niagara, Lawnchair & Kvaesitso. 

Very strange, I have no idea what can be the case then, but my guess is that it's something on your side :s
