### ISSUE TITLE
Coverage for unlisted apps with OneUI

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#2010]
Found this reddit thread and got me thinking.

https://www.reddit.com/r/oneui/comments/1auj46f/worst_part_about_installing_icon_packs_on_one_ui/

The apps in the share menu must have some kind of intent that we can tie to icons.

The apps:
- Bixby Vision (com.samsung.android.visionintelligence & com.samsung.android.bixbyvision.framework)
- Bluetooth
- Contacts (contacts > me)
- Print (default print service)
- Galaxy watch6 manager
- Private share (com.samsung.android.privateshare)
- Quick share (com.samsung.android.app.sharelive & com.samsung.android.aware.service)
- Reminder (com.samsung.android.app.reminder)

**Comment by Kaiserdragon2** [comment]
https://github.com/Kaiserdragon2/IconRequest/releases/tag/v2.3.2
I added something to the Icon Request App that might be helpful here.
It allows to query all activities.

**Comment by wwwwwwari** [comment]
My family has one of these devices luckily - working on them 👍

**Comment by Donnnno** [comment]
We have concluded that implementing this is out of our reach because Samsung doesn't provide a way currently to implement this.
