### ISSUE TITLE
[Readme] Github badge doesnt show itself

### ISSUE THREAD

**Issue by inson1** [Arcticons-Team/Arcticons#2012]
url https://camo.githubusercontent.com/35b4ec18c762358fb784f9e973f77cf6eb596f2240e69a4c6c093a836655d889/68747470733a2f2f692e6962622e636f2f71306d6463345a2f6765742d69742d6f6e2d6769746875622e706e67

![chrome_UhXEGfvnyS](https://github.com/Arcticons-Team/Arcticons/assets/75314629/5b210cce-770e-4d76-9291-13b3e73e7c59)

**Comment by Donnnno** [comment]
Yeah, there's a fix tho, just gotta merge it https://github.com/Arcticons-Team/Arcticons/pull/1996/files#diff-2678bde2086f507ce5283bc5bd9c76962ec7beb76bd42fb20cd0be9a0e200410

**Comment by inson1** [comment]
@Donnnno sorry I looked only in issues

**Comment by Donnnno** [comment]
No worries, it isn't merged yet, so it's still an issue
