### ISSUE TITLE
Icons are shuffled on ColorOS phones

### ISSUE THREAD

**Issue by JRBros2346** [Arcticons-Team/Arcticons#2018]
i have been using arcticons for a while, but for a few days, a lot of icons are jumbled up. i tried unapply and reapplying the pack and uninstall reinstall. These icons are still the same. I use Color OS, from FDroid. I added a attachment of all the wierd icons i could spot
![Screenshot_2024-02-26-17-31-05-40_92b64b2a7aa6eb3771ed6e18d0029815.jpg](https://github.com/Arcticons-Team/Arcticons/assets/85472438/3b4c4832-0b87-4efe-9b4e-7f67e50c5796)

list: 
Calculator
Camera
Calender
Candle (FDroid)
ChatGPT
Chrome
Clock
Drive
FDroid
Firefox
Game Space
Github
Instagram
Mincal Widget (FDroid, not transparent, but like translucent)
Phone
Shareit
Snaptube
Telegram
Truecaller
Unexpected Keyboard (FDroid)
VodafoneIdea
Weather
Whatsapp
Youtube

Lot of these icons, i have never seen before

**Comment by Donnnno** [comment]
Hi, this seems more like a launcher bug, than an icon pack bug. 
What launcher are you using, and have you tested it with another one?

**Comment by JRBros2346** [comment]
I'm using Color OS launcher, i haven't tested in other launchers. I don't have anymore phones. I'm using Oppo model phone

**Comment by JRBros2346** [comment]
I'm using Color OS launcher, i haven't tested in other launchers. I don't have anymore phones. I'm using Oppo model phone

**Comment by Donnnno** [comment]
Can you test it with a launcher like nova? From what I know, Color OS has some weird icon pack bugs like this.

**Comment by JRBros2346** [comment]
Ok i'll try it

**Comment by JRBros2346** [comment]
It works now, but nova launcher feels new to me. Will this be fixed in next update?

**Comment by Donnnno** [comment]
I can't say, because the ColorOS issue has been here for a while now, and I have no idea what's wrong and how to fix it.

**Comment by JapanYoshi** [comment]
I’ve encountered the same error on [Dollphone](https://github.com/japanyoshi/dollphone-foss). Here are my observations:

1. The error occurs when updating the app to a newer version while it is still applied on ColorOS Launcher.
2. App icons are replaced with those close to them alphabetically, e.g.:
  * **ma**ps → **ma**rkor
  * **play**_store → **play**ing_cards
  * **w**eight_tracker → **w**ikipedia
3. App icons earlier in alphabetical order were unaffected, e.g. barcode_scanner, camera

My best guess is that this is a cache/index error in ColorOS Launcher, where the addition of new icons to the pack do not change the index ColorOS Launcher uses to refer to the icons, therefore causing the launcher to reference the wrong image.

How I fixed my issue is as follows:

Step 1: Open Settings
![Screenshot_2024-03-23-13-17-30-45_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Arcticons-Team/Arcticons/assets/8707990/c5d5a497-8960-43a5-bb9e-2bfcb4fee39a)

Step 2: Navigate to App management
![Screenshot_2024-03-23-13-17-34-29_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Arcticons-Team/Arcticons/assets/8707990/679c057e-bfaf-45b3-ac77-d26b0baa2c43)

Step 3: Navigate to App list
![Screenshot_2024-03-23-13-17-42-47_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Arcticons-Team/Arcticons/assets/8707990/a4ebb3aa-55fc-4906-a3b9-187dce475439)

Step 4: Select System Launcher
![Screenshot_2024-03-23-13-17-47-34_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Arcticons-Team/Arcticons/assets/8707990/dbafeb46-dcc0-4b45-b48d-4216fb28e199)

Step 5: Select Storage usage
![Screenshot_2024-03-23-13-17-51-82_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Arcticons-Team/Arcticons/assets/8707990/50d71227-870a-4a04-86cd-c4052b43daaa)

Step 6: Clear cache

**Comment by Donnnno** [comment]
Thanks for the guide, I'll implement it in the wiki!
