### ISSUE TITLE
[QUESTION] Is it possible to create icons for apps without icons?

### ISSUE THREAD

**Issue by GuiSousa135** [Arcticons-Team/Arcticons#2020]
![Screenshot_20240304-225304_Lawnchair](https://github.com/Arcticons-Team/Arcticons/assets/55188286/ee928aa3-730e-485d-be45-fe70405f45bf)

This is an example, the Hidded Magisk Manager.

**Comment by Donnnno** [comment]
@GuiSousa135 can you gather the component info using icon request? I'll add a default android icon to it :)

**Comment by Donnnno** [comment]
Closing this.

Summing it up.
1. You can create loose icons for webapps, emoji's or alternative icons etc.
2. You can use an existing icon and link it in the appfilter to the right line corresponding to the new app.
3. You can long-press an icon in your launcher to edit it and pick a custom one.
