### ISSUE TITLE
SZ icon duplicate

### ISSUE THREAD

**Issue by trautb** [Arcticons-Team/Arcticons#2055]
Hi,

the SZ ("Süddeutsche Zeitung") has two apps - one for news and for for the eMagazine. In the current icon pack there are three entries for apps regarding the SZ:
```
	<!-- SZ -->
	<item component="ComponentInfo{de.sueddeutsche/de.sueddeutsche.LauncherActivity}" drawable="sueddeutschezeitung"/>

	<!-- SZ -->
	<item component="ComponentInfo{de.sde.mobile/de.swmh.oneapp.MainActivity}" drawable="sz_zeitung"/>
	<item component="ComponentInfo{de.sde.mobile/de.swmh.szapp.MainActivity}" drawable="sz_zeitung"/>
```
The two icons are almost (but not completely, only spacing is different) identical. 
I would suggest merging the entries to:
```
	<!-- SZ -->
	<item component="ComponentInfo{de.sueddeutsche/de.sueddeutsche.LauncherActivity}" drawable="sz_zeitung"/>
	<item component="ComponentInfo{de.sde.mobile/de.swmh.oneapp.MainActivity}" drawable="sz_zeitung"/>
	<item component="ComponentInfo{de.sde.mobile/de.swmh.szapp.MainActivity}" drawable="sz_zeitung"/>
```

Best,
Benedikt

P.S.:
The "sueddeutschezeitung"-icon:
![sueddeutschezeitung](https://github.com/Arcticons-Team/Arcticons/assets/64924929/f384b891-74d1-4036-a462-d27f8e5a11ea)
The "sz_zeitung"-icon:
![sz_zeitung](https://github.com/Arcticons-Team/Arcticons/assets/64924929/b15f37db-f9e3-42ff-aa5e-8a34803b6b69)

P.P.S:
If you want I can just include this in my next pull request.

**Comment by Donnnno** [comment]
Thanks for letting me know, I'm making a list of duplicates, because I have found some more already :)
