### ISSUE TITLE
Provide more context on how to change colors

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#2075]
Need to think of a clever way to help people understand how Material You icon packs work. I'm getting lots of negative review from people who don't understand that, it's a system setting, or a launcher setting that controls it.

The supported help page might also be good for this: https://github.com/Arcticons-Team/Arcticons/wiki/Supported-Launchers 

For example:
System settings > Wallpaper & Style > Color palette

**Comment by Kaiserdragon2** [comment]
How about something like this inside the app.
![image](https://github.com/Arcticons-Team/Arcticons/assets/8929967/e1791fd4-e734-4e86-9538-762592d0c3f3)

**Comment by Donnnno** [comment]
https://docs.arcticons.com/faq#how-do-i-change-my-material-you-color-palette
