### ISSUE TITLE
Update old/incorrect icons

### ISSUE THREAD

**Issue by GuiSousa135** [Arcticons-Team/Arcticons#2080]
Some of the following apps are outdated or even wrong, they are apps that I use on a daily and many are well known:

AntennaPod (F-Droid)
https://f-droid.org/packages/de.danoeh.antennapod/

Amazon Shopping (Play Store)

Unitto Calculator (F-Droid)

Record You (F-Doid)
https://f-droid.org/packages/com.bnyro.recorder/

FlorisBoard (F-Droid)
https://f-droid.org/packages/dev.patrickgold.florisboard/

Breezy Weather (F-Droid)

**Comment by Donnnno** [comment]
Hi thanks for the heads up! 

I don't see any problem with most of them tho

**Comment by aloxe** [comment]
Breezy Weather (F-Droid)
https://f-droid.org/en/packages/org.breezyweather/

Unitto is gone from F-droid
https://www.reddit.com/r/fossdroid/comments/1b6yo09/what_happened_to_unitto/

**Comment by wwwwwwari** [comment]
So to summarize, these are the icons you've mentioned:

| Link | Icons in your links/references | Arcticons | Arcticons file name |
| --- | --- | --- | --- |
| [AttennaPod](https://f-droid.org/packages/de.danoeh.antennapod/) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/a95ff40f-a1b4-4ca7-9318-5545ba7e8fc8) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/a44c5cf9-97f5-46de-9fe9-501947f96932) | antennapod.svg |
| [Amazon Shopping](https://play.google.com/store/apps/details?id=com.amazon.mShop.android.shopping) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/1ba8c94d-96d1-455c-bf83-534723bc1a89) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/6e904e25-daec-4c14-9863-175ac26e6e4c) |amazon_shopping.svg |
| [Unitto Calculator](https://web.archive.org/web/20240301195049/https://f-droid.org/packages/com.sadellie.unitto/) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/de2c7d9f-6306-44e6-8d67-1e84f9559196) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/7aea8b55-175f-4f90-aaa5-519b1f9a8ee5) | letter_uppercase_square_u.svg | 
| [Record You](https://f-droid.org/packages/com.bnyro.recorder/) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/27a06236-af3a-433b-9949-18c1307d1e5d) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/dae1e0d2-73cb-4479-b5ef-5e5c146b3f01) | record_you.svg |
| [FlorisBoard](https://f-droid.org/packages/dev.patrickgold.florisboard/) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/090776c6-a4c2-4778-b62b-381047331d50) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/81871d9b-30d6-4eb4-84d1-d6fdfc42896e) | florisboard.svg | 
| [Breezy Weather](https://f-droid.org/en/packages/org.breezyweather/) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/cf9af18b-2d4d-4671-b36a-a4a79ef28032) | ![image](https://github.com/Arcticons-Team/Arcticons/assets/89649458/ef8e439b-662f-4f76-a7e4-f99c9818c17d) | breezyweather.svg |

There are some varying degrees of differences which I can probably send a fix in a day or two if no one isn't already on it yet 😀 

I'm not sure about the Amazon Shopping one, though. With the current one, it is fairly easy to tell it apart from other Amazon icons. If we want to change, I think we can just use [amazon.svg](https://github.com/Arcticons-Team/Arcticons/blob/main/icons/black/amazon.svg), currently assigned to what I think was the [old tablet version of the same app](https://amazon-for-tablets.en.uptodown.com/android).

@Donnnno your thoughts?

**Comment by wwwwwwari** [comment]
It seems #2123 is already fixing all of this except the Amazon Shopping one.

**Comment by alix-guillard-deltatre** [comment]
Yep I did forget the Amazon one late at night. Feel free to upgrade my PR if you feel it's worth it.

**Comment by aloxe** [comment]
Yep I did forget the Amazon one late at night. Feel free to upgrade my PR if you feel it's worth it. Personally, I like it the way it is.

**Comment by Donnnno** [comment]
Made some small changes to @aloxe work, it's great tho!

I prefer the Amazon shopping one we currently have over the official icon, but I'm not using the app, so I'mn not against having the more official one instead (or as alt)

![332033491-275f14ab-e727-4f2b-a268-d2ef554a6615](https://github.com/Arcticons-Team/Arcticons/assets/31142286/7d365023-bdf7-4d77-875d-46403d7abaad)
