### ISSUE TITLE
Slight Material You colour tinge in certain icons in regular Arcticons pack

### ISSUE THREAD

**Issue by Elaborendum** [Arcticons-Team/Arcticons#2081]
For some reason, when searching for an icon to choose from in the Kvaesitso launcher, some icons appear to have a slight tinge of the main colour of my current Material you set up. This stays after choosing the icon.

Here's an image of what it looks like if I search the word "chat", the icon for FluffyChat is normal while one of the DeltaChat ones has a slight tinge of brown.
![imagen](https://github.com/Arcticons-Team/Arcticons/assets/71190696/b6bddd21-3e20-4983-9b5a-8a53961719fd)

When looking them up in the Arcticons app itself, they appear normally, without the tinge.

**Comment by Donnnno** [comment]
I'm a bit too color-blind to see this 😬

**Comment by Donnnno** [comment]
Ahh, I understand it now. You probably have the paintbrush icon enabled. That means that icon packs will recolor to the Material You color palette!

**Comment by Donnnno** [comment]
Please check these settings, if everything doesn't work, open up a bug report at the Kvaesitso launcher repository:


https://github.com/Arcticons-Team/Arcticons/assets/31142286/d2eeee2b-7ec5-4cdb-b46f-81642a683879

**Comment by Donnnno** [comment]
Closing this because it seems more like a launcher bug to me.
