### ISSUE TITLE
comdirect apps + sonos icon updates

### ISSUE THREAD

**Issue by ChaosNicro** [Arcticons-Team/Arcticons#2117]
Hey there,

Just wanted to note that the comdirect banking-app has an icon, but is not auto-detected correctly. The Tan-app for it does not have an icon yet but the auto-generated path-tracing is very good and might be usable as-is.

I also just noticed that Sonos does not apply it's icon automatically. 

Here are the relevant info-blocks:

comdirect
[de.comdirect.app/de.comdirect.core.feature.splash.](https://de.comdirect.app/de.comdirect.core.feature.splash.SplashActivity)[SplashActivity](https://de.comdirect.app/de.comdirect.core.feature.splash.SplashActivity)
https://f-droid.org/en/packages/de.comdirect.app/

photoTAN
com.comdirect.phototan/de.comdirect.phototan.feature.splash.impl.SplashActivity
https://f-droid.org/en/packages/com.comdirect.phototan/

Sonos
com.sonos.acr2/com.sonos.passport.ui.launcheractivity.LauncherActivity
https://f-droid.org/en/packages/com.sonos.acr2/

**Comment by Kaiserdragon2** [comment]
I have added the comdirect app and the Sonos one to the appfilter file these should work in the next release.
For the PhotoTan it might be best to request it through the Arcticons app or draw it yourself.

**Comment by wwwwwwari** [comment]
I added photoTAN in #2128 since I think it's still available at [Google Play](https://play.google.com/store/apps/details?id=com.comdirect.phototan) with the exact component string.

**Comment by ChaosNicro** [comment]
> I added photoTAN in #2128 since I think it's still available at [Google Play](https://play.google.com/store/apps/details?id=com.comdirect.phototan) with the exact component string.

Thanks for picking this up, looks good. Though I would suggest keeping the "C" as an outline instead of a single line, that way it can match the main app.

**Comment by wwwwwwari** [comment]
I can change the shape of the C to look like the original icon instead of using the Arcticons font. The changes won't be in this release, though.
