### ISSUE TITLE
[help] Icon appears in website but not in my homescreen

### ISSUE THREAD

**Issue by PanDabStudios** [Arcticons-Team/Arcticons#2136]
Info:
Pixel 6 128
Calyx OS
Nova launcher 8.0.18 (aurora store).
Articons material v9.2.4 (fdroid)

All icons work fine, except for a few. Here is some info on two of them:

Claro Flex (aurora store) - Appears as an icon on the website and source code, but not on my home screen
Sound Meter (fdroid) -  Appears as an icon on the website and source code, but not on my home screen

**Comment by dgcampbe** [comment]
Sounds like the appfilter entries for those apps needs to be updated. You can acquire the XML snippets needed to update then using an app like [IconRequest](https://github.com/Kaiserdragon2/IconRequest).

**Comment by PanDabStudios** [comment]
doing a quick crtl + f in the appfilter.xml file, I don't seem to find any mention of the claro flex app whatsoever [there are a ton of other claro apps declared tho], so maybe it is missing.

Now the sound meter logo seems to be pointing to com.gamebasic.decibel, which I believe is another sound meter available in the google play store [non free, with ads, and the developers website is some sort of chinese mess], maybe the way to go with this one is to also add the app ID for the free one that I am using? 

 Here is the code I got from IconRequest for both of them: 
```
<appfilter>

	<!-- Claro flex -->
	<item component="ComponentInfo{br.com.claro.flex/br.com.claro.flex.features.splash.ui.SplashActivity}" drawable="claro_flex"/>

	<!-- Sound Meter -->
	<item component="ComponentInfo{com.splendapps.decibel/com.splendapps.decibel.MainActivity}" drawable="sound_meter"/>

</appfilter>
```

**Comment by wwwwwwari** [comment]
Icons should now be fixed in the latest release 🙂

![Screenshot_2024-06-02-18-14-43-65_3822ac0e29cfec8970059bb21d01f05e.jpg](https://github.com/Arcticons-Team/Arcticons/assets/89649458/64611732-90f6-4904-aa85-91d59544054f)

**Comment by Donnnno** [comment]
thanks for the fix @wwwwwwari !
