### ISSUE TITLE
Border radius is still 2px

### ISSUE THREAD

**Issue by Npepperlinux** [Arcticons-Team/Arcticons#2149]
![Screenshot from 2024-06-02 23-24-02](https://github.com/Arcticons-Team/Arcticons/assets/66727014/ef1712d3-38ca-4fae-a34b-ebcb647b8a32)

There are other icons that need to be updated.

**Comment by Donnnno** [comment]
Aaa I was pretty sure I had converted those, but apparently not. Will add it on my to do list!

**Comment by Donnnno** [comment]
If you see other icons as well, please let me know!

**Comment by Donnnno** [comment]
![Screenshot_20240604_090631_Arcticons.jpg](https://github.com/Arcticons-Team/Arcticons/assets/31142286/5ed08d78-ca7e-43c5-9323-a1f92319a84f)

I missed more than I thought 😅

**Comment by Npepperlinux** [comment]
> ![Screenshot from 2024-06-02 23-24-02](https://private-user-images.githubusercontent.com/66727014/336250688-ef1712d3-38ca-4fae-a34b-ebcb647b8a32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDQwMTcsIm5iZiI6MTcxNzUwMzcxNywicGF0aCI6Ii82NjcyNzAxNC8zMzYyNTA2ODgtZWYxNzEyZDMtMzhjYS00ZmFlLWEzNGItZWJjYjY0N2I4YTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDEyMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YjZlM2ExN2Y0NjM4M2ZmY2RmMjUzOTc2NGYxNzM1OWRlNDJmMjA3OWZkMjMwNzg5YTI3NjQyNGQ1MTZmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.haqI70pNgKoLFWQHZHlqlvw2c-aNWd4HgGszkfXpS0E)
> 
> There are other icons that need to be updated.

Related to #2145 🤯

![Screenshot from 2024-06-04 21-17-56](https://github.com/Arcticons-Team/Arcticons/assets/66727014/77df7ee5-d6de-4be5-b396-5c8cdcf30588)

**Comment by Donnnno** [comment]
Oof! that some messy work from me!

**Comment by Npepperlinux** [comment]
> If you see other icons as well, please let me know!

- adblockbrowser
- besoccer
- aviasales
- bestsign_app
- billthefarmercrossword
- bring
- camera_pro
- banco_estado
- baresip
- blemonitor
- aard

I only looked at the A to B range, but it's hard to determine which need to be updated.

**Comment by Donnnno** [comment]
Thanks! I've looked to all of them this morning, the screenshot is 0-Z, but I might have missed the ones you listed!

**Comment by Donnnno** [comment]
Added them to the list! Apparently, I missed 150~ icons 🙃

**Comment by Npepperlinux** [comment]
While editing #2217 , I found an uncensored icons:

- calculatorpluspluswindowed
- editor
- elisa
- eventyayattendee
- flowfree
- flowfreebridges
- globoplay
- gls
- maze
- petal_maps
- petrocanada
- samsungpaymini
- saucenao
- sensorz
- shizuku
- slickdeals
- smart_home
- spowlo
- sso_connect
- super_sus
- superfreezz
- text_master_ocr
- tsuki_odyssey
- twenty
- yahoo_mail

![Screenshot_20240729-194200_Arcticons](https://github.com/user-attachments/assets/d962d860-4755-472f-9f78-ba27dff12d8b)

**Comment by Donnnno** [comment]
omg thank you! I'll change them :)
