### ISSUE TITLE
MJ pdf icon not applying

### ISSUE THREAD

**Issue by Richard38907** [Arcticons-Team/Arcticons#2150]
Since the 2.2.1 version of MJ pdf reader, the icon doesn't apply.

**Comment by Donnnno** [comment]
They most likely have updated some things causing it not to work anymore.
Can you send the appfilter code here? You can gather it with icon request:
https://play.google.com/store/apps/details?id=de.kaiserdragon.iconrequest

**Comment by Richard38907** [comment]
<appfilter>

	
	<item component="ComponentInfo{com.gitlab.mudlej.MjPdfReader/com.gitlab.mudlej.MjPdfReader.ui.main.MainActivity}" drawable="mj_pdf"/>

</appfilter>

**Comment by Donnnno** [comment]
thanks, I've added it :)
