### ISSUE TITLE
Bring back the old LibreTube Icon

### ISSUE THREAD

**Issue by WreckingBANG** [Arcticons-Team/Arcticons#2158]
I get the message of the new icon, but i dont think it looks as clean as the old icon. 

I also think it is easier for most people if the app icon is closer to the original icon, than having a completly different icon.

This is just my opinion.

This is the new icon:

![Screenshot_20240609-205717 (1)](https://github.com/Arcticons-Team/Arcticons/assets/86848811/3abe93b2-ffd3-4abe-b0cf-a0f79a370a4b)

This is the original icon:

![Screenshot_20240609-210152 (1)](https://github.com/Arcticons-Team/Arcticons/assets/86848811/808204d8-c3d7-4191-9a89-52de468cf9cb)

**Comment by WreckingBANG** [comment]
Never Mind, sorry seems to be fixed in version 3.19.1

**Comment by Donnnno** [comment]
Haha got quite some responses about this one. It wasn't intentional, but mistakes happen :) 
https://github.com/Arcticons-Team/Arcticons/issues/2145
