### ISSUE TITLE
InnerTune App is no longer updated - Request

### ISSUE THREAD

**Issue by Richard38907** [Arcticons-Team/Arcticons#2170]
InnerTune is no longer updated. These two variants are currently in use. Could you make icons for these one?

<appfilter>

	
	<item component="ComponentInfo{com.Arturo254.innertune/com.malopieds.innertune.MainActivity}" drawable="innertune"/>

	
	<item component="ComponentInfo{com.malopieds.innertune/com.malopieds.innertune.MainActivity}" drawable="innertune1"/>

</appfilter>

**Comment by Mrunknow3** [comment]
They are the developer of a innertune that has not been updated, and glitch so much comes.
