### ISSUE TITLE
Allow time widget to open non-standard clock app

### ISSUE THREAD

**Issue by alchemiker** [Arcticons-Team/Arcticons#2174]
Hello, I installed the open-source app https://github.com/BlackyHawky/Clock to replace the standard android clock app, which I couldn't de-install, but deactivated at least. 
But now I cannot open the clock app with a tap on the time widget from Arcticons on my homescreen, as I used to. 
Is there something that can be done about it? I would like the new clock app to open up when I tap the time widget on my screen.
I know I could just use the widget of the new clock app instead (and I will do now), but I really love the font of the Arcticons time widget 🥰 seeing the handwrite-style numbers and letters brings good mood!

**Comment by Donnnno** [comment]
Looks like @Kaiserdragon2 found a fix! This was bugging me too btw 😅

**Comment by Donnnno** [comment]
https://github.com/user-attachments/assets/7206090d-a039-4950-b72c-e94acee830c3

Can confirm that it works. The first clock is the old version, the second the debug version (newest)
