### ISSUE TITLE
Request Dashboard not mentioned in new Docs

### ISSUE THREAD

**Issue by Kaiserdragon2** [Arcticons-Team/Arcticons#2178]
There should be some Info about https://www.arcticons.com/requests after the Contributing Guide in the Gitbook for people who like to help with the requested icons.
Also is there a way to contribute to the Gitbook ?

**Comment by Donnnno** [comment]
Yes ofcourse! I'll add it :-)

**Comment by Donnnno** [comment]
Oh I can send you an invite for the gitbook team if you want :-)
