### ISSUE TITLE
Request Site on Mobile

### ISSUE THREAD

**Issue by Kaiserdragon2** [Arcticons-Team/Arcticons#2211]
The top over the table isn't really usable on mobile. I think most people will use it on a PC, but it should be edited a bit to make it somewhat usable![Screenshot_20240723-212045.png](https://github.com/user-attachments/assets/32d7dd9e-88ff-4b59-bb09-ef62adeaaea7)

The search input on the updatable side doesn't look good either.

**Comment by Donnnno** [comment]
Time to implement the hamburger menu for mobile! 
(I'll take a look at it)

**Comment by Kaiserdragon2** [comment]
With the latest css changes it is usable now
