### ISSUE TITLE
Use GitHub to build APKs for releases, instead of me on my local pc

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#2214]
H o w  d o  t h e s e  a c t i o n s  w o r k  t h o ?

**Comment by Kaiserdragon2** [comment]
I will create an action to do the build

**Comment by Kaiserdragon2** [comment]
We have the option to create a release manuelly and the action just uploads the apk or
we could create the release when a new tag is created and the release is build automatic the text body can be stored in a file.
Which one would you like more?
