### ISSUE TITLE
Documentation update ?

### ISSUE THREAD

**Issue by PurpleBabar** [Arcticons-Team/Arcticons#2224]
Hi everybody and thanks for Arcticons it's great :fire: :fireworks: :smiley: 

I would like to contribute but I find myself a little bit lost when reading the Contribute > Creating Icons guide:

```
The size of your document should always be 48×48 px.
Every line has a stroke thickness of 1 px and the color should always be #ffffff (white).
Dots are 1,5×1,5 px and have a fill that should also be white.
The maximum size of your icon should fit into the template circle icon (43×43 px).
Square-like icons should fit into the square template.
Rectangular icons should fit into the rectangle templates. 
```

For the size of the document and stroke thickness I get it ;)

For the dot: should it be a circle with no stroke but a fill ? 
Should the icon fit the circle even if it's not in a circle ? (I checked other pull requests and some of the icons don't fit in a circle of 43x43 :thinking: ) 
For the square and the rectangle there is no size specified

Maybe giving a few examples with well known apps in this part of the documentation would be beneficial :smiley: 

Can you/we update the documentation to make it more understandable ? :smiley:

I just wanna make sure I get the guidelines right since I would like to contribute for about 70 icons :smile: 
Thanks for your answers :smiley:

**Comment by Donnnno** [comment]
Hi! Great to hear that! 
Thanks for your feedback, it's always good to see where we can improve :-) 

1. The dot should have no stroke, but a fill indeed.
2. generally the icons should fit in the circle for the best sizing, but there are some exceptions. And with sizing: it's really hard to be consistent, hence why the basic principles are there.
3. You can find the square and rectangle sizes inside the actual template files, but it's a good idea to add them to the documentation.
4. I'll think about some example apps and the exceptions. But some that come to mind are: WhatsApp & Signal for icons that go beyond the circle. 



Also, 70 icons 👀 ?! (nice)

**Comment by PurpleBabar** [comment]
Hey :) 

Where should I modify the documentation ? :) I see that in the guides.md file some of the infos are more explicit :) 

1. Perfect :) 
2. I will then try to make all icons fit in 43x43px ;) 
3. Perfect :D specifying it in the docs is really easy then :) (maybe add link to the files ?)
4. Whatsapp and Signal, but we could also give example for square app (facebook ?) and for rectangle app (I don't think of one right now :thinking: )

Also last questions, but do all letters need to come front arcticons font ?  (I have the Swile app which is a font slightly altered, should this be all arcticons font or some from the font and some drawn ? :))

Thanks a lot :) 

(a lot of the applications I'm making are for personnal use but are used a lot in France so I hope they'll benefit others ;) )

**Comment by Donnnno** [comment]
For the font look inside the template folders, there's an SVG document with all glyphs you need.
My preference is to use that for consistency, buy you can always make stylistic alternates. 

Documentation updates are not possible through GitHub anymore because it's hosted on GitBook now. But let me know your suggestions and I'll add them!
