### ISSUE TITLE
Bug app missing in request page

### ISSUE THREAD

**Issue by Richard38907** [Arcticons-Team/Arcticons#2252]
Instagram Lite 
com.instagram.lite
This app has no icon and is missing on the request page
![Screenshot_20240811-154817_Arcticons Black.png](https://github.com/user-attachments/assets/84c3da66-b594-45ab-9522-7645396f34cc)

**Comment by Donnnno** [comment]
Please send the icon with icon request here :) 
https://play.google.com/store/apps/details?id=de.kaiserdragon.iconrequest&hl=en

**Comment by Richard38907** [comment]
![11082024_163241.zip](https://github.com/user-attachments/files/16574024/11082024_163241.zip)

**Comment by Richard38907** [comment]
The "cat" shape is my system's shape. I didn't realize that the shape would be exported with😅.

**Comment by Npepperlinux** [comment]
> ![11082024_163241.zip](https://github.com/user-attachments/files/16574024/11082024_163241.zip)
>>```xml
>><appfilter>
>>
>>        
>>        <item component="ComponentInfo{com.instagram.lite/com.facebook.lite.MainActivity}" drawable="instagram_lite"/>
>>
>></appfilter>
>>```

It seems that the code is already included in line 15067 of the appfilter.xml.

**Comment by Donnnno** [comment]
Ah, gotta change the drawable to instagram instead of instagram_lite

**Comment by Npepperlinux** [comment]
> It seems that the code is already included in line 15598 of the appfilter.xml.

...as "Instagram".
![image](https://github.com/user-attachments/assets/8a40e2dc-c9e3-4afc-875e-4a6b233d28cb)
The Zip file contained a cat-shaped icon, so maybe that has something to do with it?

**Comment by Richard38907** [comment]
switched back to default shape
![11082024_180131.zip](https://github.com/user-attachments/files/16574258/11082024_180131.zip)

**Comment by Npepperlinux** [comment]
This could be a problem with the launcher you are using. I would suggest that reviewing your launcher settings or initializing the settings and reapplying the icon pack might change something.

**Comment by Richard38907** [comment]
I have the problem on my two phones with two different launchers (Lawnchair and OnePlus launcher) The Instagram lite icon doesn't exist in the icon pack.
![Screenshot_20240813-105504_Arcticons Black.png](https://github.com/user-attachments/assets/1cea167b-6f62-4b97-a868-58d4409cf957)

**Comment by Npepperlinux** [comment]
> I have the problem on my two phones with two different launchers (Lawnchair and OnePlus launcher) The Instagram lite icon doesn't exist in the icon pack. ![Screenshot_20240813-105504_Arcticons Black.png](https://private-user-images.githubusercontent.com/148692265/357342570-1cea167b-6f62-4b97-a868-58d4409cf957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDA2NzIsIm5iZiI6MTcyMzU0MDM3MiwicGF0aCI6Ii8xNDg2OTIyNjUvMzU3MzQyNTcwLTFjZWExNjdiLTZmNjItNGI5Ny1hODY4LTU4ZDQ0MDljZjk1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwOTEyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2Y5MGRkYTUxYWVkNzVlYjNkNmY1NGNmMDdlMjJmNTFjZmVjODk1Y2Q4NzE5YmVjYzJhNTA4OGMwMzRmMDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RsZlWkZKRhA2BiIwDVdfQ92IJ3pPmEMeHjpzV9M4a-A)

Arcticon shares the "Instagram" icon with "Instagram Lite" (it does not have a dedicated "Instagram Lite" icon), so if you want to apply the icon manually, you need to select the "Instagram" icon.

**Comment by wwwwwwari** [comment]
So is the problem:

1. The Instagram Lite app shows the Instagram icon from the Arcticons pack and @Richard38907 just want a dedicated icon, or...
2. The Instagram Lite app shows the default, non Arcticons icon (somehow)?

**Comment by Richard38907** [comment]
@wwwwwwari The second proposition is right

**Comment by Npepperlinux** [comment]
@Richard38907 Have you tried setting up Lawnchair to apply changes to all icons? (Home Settings -> General -> Icon Style -> Select Icon Pack)
![arcticons_lawnchair](https://github.com/user-attachments/assets/76cce55b-416d-4a40-847b-ec9478dc8eca)
Only after installing Lawnchair did I learn that there is a way to manually set icons for each app.
![arcticons_lawnchair_instagram](https://github.com/user-attachments/assets/3813e84f-6cce-44b8-917e-fad71090f70d)![arcticons_lawnchair_instagram_2](https://github.com/user-attachments/assets/edc4c549-77af-45fd-bce2-07c59e6cb8f8)

**Comment by Richard38907** [comment]
I tried now and it applies the default Instagram icon.
