### ISSUE TITLE
Requesting For Visual Improvements Of The Icons! 

### ISSUE THREAD

**Issue by ThatAnnoyingVegan** [Arcticons-Team/Arcticons#2255]
The icons look dull and lifeless when they're small, as you can see in the screenshots provided below. If the line of the icons were a bit thicker than what it is now, it wouldn't be happening. 

![Screenshot_20240814-142931_Next_Player.png](https://github.com/user-attachments/assets/b2ccd4e6-2c4c-453c-be89-ccaeb9200f2e)

![Screenshot_20240814-143715_Next_Player.png](https://github.com/user-attachments/assets/0744ff10-5908-428f-b6f8-75b7c89d500c)

**Comment by Donnnno** [comment]
But honestly, what did you expect when you put them in those small folders.
You're better off using Lawnicons at that point.
Changing the line-width is not just a simple slider, it requires careful adjustments to thousands of icons.

**Comment by ThatAnnoyingVegan** [comment]
I literally thought it was as simple as moving a slider to change the line width, lol. Never mind. 😕
