### ISSUE TITLE
Android 12 is not required for Arcticons You

### ISSUE THREAD

**Issue by Arttast** [Arcticons-Team/Arcticons#2257]
Using EMUI 12 + Lawnchair 14 Beta 2 (here's ss for proof)(also you can adjust colors from Lawnchair)
![Screenshot_20240814_125506_app lawnchair](https://github.com/user-attachments/assets/b222437d-1ba4-400d-b724-084caa3aacfd)

**Comment by Donnnno** [comment]
Good point, there are some launchers that have their workaround indeed. But in general, most launchers require A12+ in order for it to work properly.

**Comment by Arttast** [comment]
should i make a commit adding something like
"Dynamic icons generally require Android 12 although some launchers may allow for dynamic icons to work for pre-Android 12 devices"
to the wiki

**Comment by Donnnno** [comment]
Thanks for your suggestion! I've added it to the docs :)
https://docs.arcticons.com/faq#material-you-colors

**Comment by Arttast** [comment]
Thanks!
