### ISSUE TITLE
InnerTune (Arturo 254) Rebranded

### ISSUE THREAD

**Issue by Richard38907** [Arcticons-Team/Arcticons#2259]
InnerTune (Arturo254) has now a new name due to a rebrand request from the original proprietary. More info on https://github.com/Arturo254/InnerTune/issues/79

Here is the new appfilter:

![17082024_081734.zip](https://github.com/user-attachments/files/16643703/17082024_081734.zip)

**Comment by JPGuillemin** [comment]
Hi, 

I am the designer of the new Opentune icon. It is released under le CC licence.

Please note the dark circle is part of the icon (not just a dark background). Please keep the dark circle in your interation to your icon theme. :)

Thanks
![opentune4](https://github.com/user-attachments/assets/6bd7e60d-d6db-4f13-869f-e898c071c053)

JP

**Comment by Donnnno** [comment]
We can leave the outline of the circle in there. But having a filled circle goes against the Arcticons style.

**Comment by JPGuillemin** [comment]
> We can leave the outline of the circle in there. But having a filled circle goes against the Arcticons style.

What would you do with the Youtube icon ? You remove the red disc ?

**Comment by JPGuillemin** [comment]
The colors of the icon make no sense with a white background, so you can either change/darken the inside logo for less ”light” blue , or ask the designer for a white background variant of the icon. 
But current logo colors make no sense on white background

**Comment by Donnnno** [comment]
Idk if you have an idea how Arcticons looks. But we make everything monochrome and line-based. :)

![Screenshot_20240818_133912_Niagara Launcher.png](https://github.com/user-attachments/assets/ed16b06f-5127-4f5d-805d-32e8ffff1f87)

**Comment by JPGuillemin** [comment]
OK :) so you can just tranform the icon in this way, keeping the circle around :)

**Comment by gewaleelek** [comment]
Sorry, I just noticed the new discussion here. I've added back the circle frame to the icon in 3d16b71.
