### ISSUE TITLE
Icon existing but not used on default

### ISSUE THREAD

**Issue by FireflyRobots** [Arcticons-Team/Arcticons#2331]
There are a few icons, which are not used by default, but need to be selected manually.

Example:

	<item component="ComponentInfo{de.obi.app/de.obi.app.shared.activity.SplashActivity}" drawable="heyobi"/>

![HeyObi_Niagara Launcher](https://github.com/user-attachments/assets/87a57ee8-831e-49ce-b251-ca30098a6e79)

**Comment by Donnnno** [comment]
Thx for reporting, it's most likely because of an app update!

**Comment by Donnnno** [comment]
Please report others too with the component info :)

**Comment by FireflyRobots** [comment]
sure :)

I found two more so far:

<item component="ComponentInfo{com.gls.glsone.hybridapp/com.gls.glsone.hybridapp.MainActivity}" drawable="gls_app"/>
<item component="ComponentInfo{de.materna.bbk.mobile.app/de.materna.bbk.mobile.app.ui.SplashScreenActivity}" drawable="nina"/>
