### ISSUE TITLE
Improve GH-Pages deployment and GH workflows.

### ISSUE THREAD

**Issue by Kaiserdragon2** [Arcticons-Team/Arcticons#2365]
- [x] Move GH-Pages to different Branch
- [x] Rework Workflow to not have gh-bot have the most commits

**Comment by Kaiserdragon2** [comment]
@Donnnno Could you set up an environment at the moment only main can publish gh-pages
![image](https://github.com/user-attachments/assets/2b7c2b6c-e705-4af1-9df9-71fce81ae172)
![image](https://github.com/user-attachments/assets/7f864666-be83-4e3c-ae3e-a3a99f50dcc2)

**Comment by Kaiserdragon2** [comment]
And this need probably set to GitHub Actions
![image](https://github.com/user-attachments/assets/ce395493-143c-4390-bea1-6b8e540b8b6d)

**Comment by Donnnno** [comment]
I've made you admin! I think you can change this stuff now!

**Comment by Donnnno** [comment]
I've added an environment & changed pages to GH Actions
