### ISSUE TITLE
Improve the release script to include changelog in app too.

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#2370]
It would be pretty neat if the release action can add the changelog inside the app too!

https://github.com/Arcticons-Team/Arcticons/blob/main/app/src/main/res/values/changelog.xml

**Comment by Kaiserdragon2** [comment]
I don't know if it is enough to have a changelog that only updates some value or do you want to have the ability to add some custom notes. If so i can implement something.
