### ISSUE TITLE
[Enchancement] Redo the Fossify App icons, which are using incorrect or generic icons.

### ISSUE THREAD

**Issue by voxelized-voxel** [Arcticons-Team/Arcticons#2381]
The [Fossify](https://github.com/FossifyOrg) apps are forked from the former SimpleMobileTools apps, which have been bought by ZippoApps. All Fossify apps are currently supported by Arcticons, but use incorrect or generic icons that don't match the original and their lovely design.

Here is a comparison and list of all the issues with the current icons:

* File Manager: Generic icon
* Clock: Generic icon
* Notes: Generic icon
* Launcher: Generic icon
* Camera: Generic icon (I think the generic is better than the original too)
* Keyboard: Wrong icon / SimpleMobileTools icon
* Calendar: Generic icon
* Contacts: Generic icon
* Music player: Wrong icon / SimpleMobileTools icon
* Gallery: Generic icon
* Voice recorder: Generic icon
* Calculator: Correct icon / Fossify icon
* Caller: Generic icon
* Messages: Generic icon

![edb1e030-470a-4a0a-84a4-f461f6ccc2bd](https://github.com/user-attachments/assets/568efe19-1c05-422c-90cf-80788a2ab395)
![4ffffb1b-4cc5-4008-8037-ed36e1abdb90](https://github.com/user-attachments/assets/a251ac96-4819-4970-b324-3748ca43d01a)

**Comment by Donnnno** [comment]
But they're generic apps, right?
Isn't that the entire point of fossify? The standard icons look fine to me

**Comment by Donnnno** [comment]
You are welcome to add the icons! 
Most Samsung or other icons are added by contributors who preferred the specific look of those apps.

**Comment by Donnnno** [comment]
https://docs.arcticons.com/contribute

**Comment by gewaleelek** [comment]
I've included new Fossify icons in #2408.

![image](https://github.com/user-attachments/assets/f5f9f121-b6c6-4613-99b2-dde9d193f6fc)

I tried to make them as similar to the actual icons as I could while also consistent with general Arcticons looks (avoiding double outlines and such), so they won't be 1:1 exact match with the original design.

**Comment by Donnnno** [comment]
Thanks for taking the time to create these!
