### ISSUE TITLE
Failed to build app bundle for google play

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#2394]
It has trouble reading the changelog or something?
![image](https://github.com/user-attachments/assets/11f3ac33-0403-44a1-b503-c4a56947a5c9)

**Comment by Donnnno** [comment]
new error
![image](https://github.com/user-attachments/assets/460b1cc1-8330-4191-8c74-b419709b39bd)

**Comment by Kaiserdragon2** [comment]
The second one indicates that the content of the secret is not correct

**Comment by Donnnno** [comment]
Yea I figured, but I don't know what I did wrong. Guess I'll need to try again

**Comment by Donnnno** [comment]
Is it possible to manually trigger the action? Every time I try it, it just skips the process

**Comment by Donnnno** [comment]
![image](https://github.com/user-attachments/assets/a63bd466-f026-4c9d-8f25-be8c9733e87d)

![image](https://github.com/user-attachments/assets/8c1b65bc-1604-4504-b765-bd152a4ce7b8)


SUCCESS!
