### ISSUE TITLE
[BUG] Sonic restaurant app logo is Sonic the hedgehog

### ISSUE THREAD

**Issue by candroid-man** [Arcticons-Team/Arcticons#2397]
![image](https://github.com/user-attachments/assets/2eb20b22-6782-4002-ba75-18767beeb2e8)

Additionally it would be cool to have a real Sonic logo, and I figured I'd put it here since the icon requester is probably borking out for this app. Thank you!

**Comment by candroid-man** [comment]
It's certainly funny and it does work as an indicator for what the app is lol, but I would much prefer a real icon for it

**Comment by Donnnno** [comment]
No worries I'll fix it for the next release

**Comment by Donnnno** [comment]
![image](https://github.com/user-attachments/assets/aeef9e89-4692-40cc-a04f-9b25222f8c6b)
