### ISSUE TITLE
Weird misalignments in the font template file

### ISSUE THREAD

**Issue by gewaleelek** [Arcticons-Team/Arcticons#2406]
Hi,

I don't know if it's just me, but when I open the [font template file](https://github.com/Arcticons-Team/Arcticons/blob/main/templates/arcticons_font.svg) in InkScape, some letters seem to have weird misalignments.

* Numbers: 0, 3 and 9
![image](https://github.com/user-attachments/assets/a3ca4222-d04c-4e6b-83ab-377ea23f6507) ![image](https://github.com/user-attachments/assets/bd81bac2-2fc0-44a7-be5b-2fbf9db2d4ea) ![image](https://github.com/user-attachments/assets/a2bdff7d-9af0-4982-a3bf-25ca470646fc)

* English letters: B and R
![image](https://github.com/user-attachments/assets/5afafe7f-8705-4d29-bb57-908bb5853ac4) ![image](https://github.com/user-attachments/assets/7c22974f-ca0e-40f8-8b83-b7071e0db9f9)

* Russian letters: B and э
![image](https://github.com/user-attachments/assets/ba99aadb-6fb5-4f7a-a569-b75895169431) ![image](https://github.com/user-attachments/assets/29cde0c6-b0eb-4a7a-9759-9765ebf45509)

* Greek letters: B, ξ, π, σ and τ
![image](https://github.com/user-attachments/assets/006a5062-5c31-4b1b-b3ff-ba25f7915723) ![image](https://github.com/user-attachments/assets/b98c0b26-3a0c-4975-a3dc-0770208ac7d7) ![image](https://github.com/user-attachments/assets/1619f412-187b-4a40-9e33-e0d8b0a78c5b) ![image](https://github.com/user-attachments/assets/48a32b3b-3589-4ca7-8932-5e5513858471) ![image](https://github.com/user-attachments/assets/9ccdc4ac-0c31-44a2-a632-711b5ff2a8d5)

* Last row letters (I don't know what language this is): the first one and the sixth one from the last
![image](https://github.com/user-attachments/assets/9bf926e3-be43-4caa-b609-404c4e2f15bf) ![image](https://github.com/user-attachments/assets/6434dbce-755f-4a54-a087-8f18c8dbfd8c)

I've also attached the svg file with all the red circles for your convenience.
![arcticons_font](https://github.com/user-attachments/assets/39a558fe-a5cf-4613-ab18-374f5f70e635)

**Comment by Donnnno** [comment]
Oof that's bad, it must be an exporting thing for sure, will look at this later!

**Comment by Donnnno** [comment]
Should be fixed now!
https://github.com/Arcticons-Team/Arcticons/blob/main/templates/arcticons_font.svg
