### ISSUE TITLE
Authenticator Pro got rebranded to Stratum

### ISSUE THREAD

**Issue by voxelized-voxel** [Arcticons-Team/Arcticons#2412]
The app icon is still the same, but the identifier changed and now Arcticons no longer applies the icon to the app.

https://github.com/stratumauth/app

App ID: com.stratumauth.app

**Comment by Kaiserdragon2** [comment]
Could you gather the appfilter with https://github.com/Kaiserdragon2/IconRequest

**Comment by Donnnno** [comment]
There's already a pr for this: #2396
