### ISSUE TITLE
App Icon not appearing for Articons Light

### ISSUE THREAD

**Issue by Thewisem** [Arcticons-Team/Arcticons#546]
The app Icon is not appearing for articons light. Instad the default app icon is appearing. You know the one which system apps have. (Like package installer)
Android:7.1.1 Nougat
Device: Samsung Galaxy Tab A

**Comment by Aman9das** [comment]
Can you tell the launcher n have you tried apply icon pack button?

**Comment by Thewisem** [comment]
I am using nova launcher. And the articons icon pack is working on this app. Just not the normal icon1
